- model: configuration.deployconfig
  pk: 1
  fields:
    name: 'Default configuration'
    activate_deploy: 'yes'
    start_time: '00:00'
    end_time: '01:00'
- model: configuration.globalconfig
  pk: 1
  fields:
    name: 'Default configuration'
    show_warning: 'no'
    remove_duplicate: 'no'
